### ISSUE TITLE
Full Stack projektin katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [Aikamoine/fs-project#5]
# Full Stack projektin katselmointi

Terve @Aikamoine! Tässä lyhyt katselmointi Full Stack kurssin projektistasi. Katselmoinnissa esitetyt kommentit ovat parannusehdotuksia, joita voit _halutessasi_ ottaa huomioon tässä tai tulevissa projekteissasi. Mitään muutoksia tähän projektiin ei siis ole pakko tehdä suoritusmerkintää varten.

### Mitä tein?

- Rekisteröin uuden käyttäjän
- Selasin reseptejä eri hakurajaimilla
- Lisäsin reseptejä ostoslistaan
- Selasin aineisosia
- Katsoin ja muokkasin ostoslistaa
- Kirjauduin ulos

### Kokemus

- Resepti-sovelluksen käyttöliittymää on helppo käyttää ja sen ulkoasu on tyylikäs, hyvää työtä! 🥇
- Lomakkeissa on kattavat validoinnit ja virhetilanteissa selkeät virheilmoitukset, hienoa!
- Automaattinen sisäänkirjautuminen rekisteröitymisen jälkeen nopeuttaa sovelluksen käyttöönottoa
- Reseptin sivulla "Alkuperäinen resepti" voisi olla tekstin sijaan linkki
- Ostoslistan "Resepti"-sarakkeen reseptin nimi voisi olla linkki reseptin sivulle
- Tieto onko ostoslistan ostos valittu tai ei, voisi tallentua. Nyt kun ostolista-sivulta siirtyy pois, valinnat tyhjentyvät

## Koodi

- Frontend-puolen koodi on suurimmilta osin selkeästi organisoitua, hyvä! Hakemiston components sisällä olevan hooks-hakemiston voisi ehkä siirtää client-hakemistoon. Samoin util-hakemiston services-hakemiston voisi siirtää client-hakemistoon
- [usePasswordValidaation](https://github.com/Aikamoine/fs-project/blob/main/client/components/hooks/usePasswordValidation.js#L3) hookissa ei tarvita tilaa. Sen voi yksinkertaisesti toteuttaa näin:

  ```js
  import { useMemo } from 'react'

  const usePasswordValidation = (firstPassword = '', secondPassword = '', minLength = 8) => {
    // useMemo:n käyttö on pientä hifistelyä, sitä ei periaatteessa tarvita https://reactjs.org/docs/hooks-reference.html#usememo
    return useMemo(() => ({
      length: firstPassword.length >= minLength,
      upperCase: firstPassword.toLowerCase() !== firstPassword,
      lowerCase: firstPassword.toUpperCase() !== firstPassword,
      hasNumber: /\d/.test(firstPassword),
      specialChar: /[ `!@#$%^&*()_+\-=\]{};':"\\|,.<>?~]/.test(firstPassword),
      match: firstPassword === secondPassword,
    }), [firstPassword, secondPassword, minLength]);
  }

  export default usePasswordValidation
  ```

- API-kutsut on abstrahoitu hyvin uudellenkäytettäviksi palveluiksi
- Ehkäpä [tälle](https://github.com/Aikamoine/fs-project/blob/5dc73f42e9d8e41b2f97b36a43531ae74f586006/client/util/common.js#L9) parempi nimi olisi `getConfig`?
- API-kutsuihin liittyvät operaatiot tuottavat usein jonkin verran toisteellista [boilerplate-koodia](https://github.com/Aikamoine/fs-project/blob/5dc73f42e9d8e41b2f97b36a43531ae74f586006/client/components/RecipeView/index.js#L12). Esimerkiksi [React Query](https://react-query.tanstack.com/) -kirjaston avulla API-kutsut voi helposti abstrahoida yksinkertaisiksi, uudelleenkäytettäväksii hookeiksi, kuten `useRecipes()`
- Lomakkeiden tilanhallinta on hoidettu melko siististi, mutta kun lomakkeen koko kasvaa tai sen logiikka monimutkaistuu, on usein kätevää käyttää jotain lomakkeen tilanhallinnasta vastaavaa kirjastoa, kuten [Formik](https://jaredpalmer.com/formik)
- Myös backend-puolen koodi on selkeästi organisoitua, hienoa!
- [HTTP-pyynnöissä](https://github.com/Aikamoine/fs-project/blob/5dc73f42e9d8e41b2f97b36a43531ae74f586006/server/controllers/ingredientsController.js#L61) voi hyödyntää myös Noden puolella Axiosta. 
- `res.json`- ja `res.send`-kutsujen yhteydessä `toJSON`-metodia ei tarvitse erikseen kutsua. Kun JSON-muotoinen vastaus muodostetaan, `JSON.stringify`-metodi kutsuu sitä automaattisesti
- Kontrollereiden  `try { ... } catch (e) { ... }`-lohkojen sijaan kannattaa hyödyntää [express-async-errors](https://www.npmjs.com/package/express-async-errors)-kirjastoa ja keskittää virheiden käsittely yhteen middlewareen

## Kokonaisuus

Resepti-sovelluksesta löytyy tarvittava toiminallisuus reseptin etsimiseen ja ostolistojen muodostamiseen valittujen reseptien pohjalta. Sovellusta on helppo käyttää, eikä ainakaan katselmoinnin aikana käytössä ilmennyt bugeja, tai erityisiä käytettävyyteen liittyviä ongelmia. Projektin koodi on suurimmilta osin järkevästi organisoitua ja sen laatu on pääosin korkea, vaikka pieniä parannuskohteita löytyikin. Hyvää työtä!

**Comment by Aikamoine** [comment]
Kiitos perusteellisesta katselmoinnista ja hyvistä kehitysideoista! Projektin kehitys on nyt muiden kurssien takia telakalla ainakin toistaiseksi, mutta itse tätä ohjelmaa ainakin tykkään käyttää, joten kehitys tuskin loppuu tähän :)

Tajusin, etten ollut antanut katselmointia varten minkään tasoisia pääkäyttäjä-oikeuksia, eli käyttökokemuksen testaaminen jäi vähän vajaaksi. Mutta jos tämä kuitenkin riitti kurssin testausta varten, niin hyvä näin!
